
model:

  ckpt_path: "/capacity/userdata/vcfenxd75jiv/shichenrui/ui_tars/ByteDance-Seed/UI-TARS-1.5"
  base_port: 8000
  replicas: 4

  vllm_params:
    max_model_len: 4096
    gpu_memory_utilization: 0.9
    # enforce_eager: "store_true"

# 服务配置
service:

  host: &service_host "0.0.0.0"
  service_port: &service_port 15959

  service_endpoint: "http://${service.host}:${service.service_port}"

